### ISSUE TITLE
renovate の実行間隔を長くしたい

### ISSUE THREAD

**Issue by honahuku** [koyashiro/infra#58]
aqua-registry とかは頻繁に更新が入るのでこれを都度更新するのはちょっと、という気持ちになる。  
1週間に1度くらいの実行間隔にしませんか？

**Comment by koyashiro** [comment]
> aqua-registry とかは頻繁に更新が入るのでこれを都度更新するのはちょっと、という気持ちになる。

都度更新すると具体的に何がまずいんでしたっけ？

あまり課題感を感じていないので、背景をもう少し共有してほしいです🙏

**Comment by koyashiro** [comment]
最新のバージョンを可能な限りはやく使いたいと思っているので、都度更新のほうが好ましいと思っています。

**Comment by honahuku** [comment]
技術的な面で都度更新すると困ることは無いです。  
しかし今 Discord でこのリポジトリのアクティビティを共有していること、後から見返したときに確認する PR が増えることが個人的に少し気になるかなという感じです。  

例えば Discord の該当チャンネルをミュートする、とかでも対応可能ですがそうすると Webhook を設定している意味が薄れる気はします。  
こやしろさん側で renovate や GitHub の PR を確認するコストをそれほど負担に感じていないならそのままでも大丈夫です、ここは koyashiro-infra なので

**Comment by koyashiro** [comment]
> しかし今 Discord でこのリポジトリのアクティビティを共有していること

この設定をしたときに目的を確認していなかったので、今更ながらこの場で訊いちゃうんですが Discord にwebhook 飛ばしてるのって何を確認するためでしたっけ？

レビュー依頼やメンションを見逃したくないとかであれば、リポジトリの webhook 以外の手段(リポジトリではなくユーザー側の webhook を使うとか)で解決できるかもと思ったので質問です。

> こやしろさん側で renovate や GitHub の PR を確認するコストをそれほど負担に感じていないならそのままでも大丈夫です

ここは負担に感じてないです。
